@startuml abstract_factory
hide empty members
class Client{}

interface AbstractFactory {
    +createProductA(): AbstractProductA
    +createProductB(): AbstractProductB
}

interface AbstractProductA
interface AbstractProductB

class ConcreteFactory1 implements AbstractFactory {
    +createProductA(): ConcreteProductA1
    +createProductB(): ConcreteProductB1
}
class ConcreteFactory2 implements AbstractFactory {
    +createProductA(): ConcreteProductA2
    +createProductB(): ConcreteProductB2
}

class ConcreteProductA1 implements AbstractProductA
class ConcreteProductA2 implements AbstractProductA
class ConcreteProductB1 implements AbstractProductB
class ConcreteProductB2 implements AbstractProductB

AbstractFactory <- Client
Client --> AbstractProductA
Client --> AbstractProductB
@enduml
