@startuml adapter
hide empty members

interface Target {
    +operation()
}

class Client{}

class Adapter implements Target {
    +operation()
}

class Adaptee {
    +specificOperation()
}

Client -> Target
Adapter -> Adaptee : adapts
@enduml
