@startuml chain
hide empty members
class Client{}

abstract class Handler {
    -next: Handler
    +setNext(handler: Handler): void
    +handle(request: Request)
}

class ConcreteHandlerA extends Handler {}
class ConcreteHandlerB extends Handler {}

Client -> Handler
Handler -> Handler : Преемник
@enduml
