@startuml command
hide empty members
class Client{}
interface Command {
    +execute()
}

class ConcreteCommand implements Command {
    -receiver: Receiver
    +execute()
}

class Invoker {
    -command: Command
    +setCommand(command: Command): void
    +invoke()
}

class Receiver {
    +action(): void
}

Receiver <- ConcreteCommand
Invoker o-> Command
Client --> Receiver
@enduml
