@startuml composite
hide empty members
interface Component {
    +add(component: Component): void
    +remove(component: Component): void
    +operation()
    +getChild(int): Component
}

class Leaf implements Component {
    +operation()
}

class Composite implements Component {
    +add(component: Component): void
    +remove(component: Component): void
    +operation()
    +getChild(int): Component
}

Composite o-- Component : children
@enduml
