@startuml decorator
hide empty members
interface Component {
    +operation()
}

class ConcreteComponent implements Component {
    +operation()
}

abstract class Decorator implements Component {
    -component: Component
    +Decorator(component: Component)
    +operation()
}

class ConcreteDecoratorA extends Decorator {
    -addedState
    +operation()
}

class ConcreteDecoratorB extends Decorator {
    +operation()
    +addedBehavior()
}

Decorator o-- Component
@enduml
