@startuml factory_method
hide empty members

abstract class Creator {
    +createProduct(): Product
}

abstract class Product {
    +use()
}

class ConcreteCreator implements Creator {
    +createProduct(): ConcreteProduct
}

note left of ConcreteCreator::createProduct
    return new ConcreteProduct();
end note

class ConcreteProduct implements Product {
    +use()
}

ConcreteCreator .> ConcreteProduct : <<instantiate>>

@enduml
