@startuml flyweight
hide empty members

class Client{}

class Flyweight {
    +operation(extrinsicState)
}


class FlyweightFactory {
    +getFlyweight(key): Flyweight
}

class ConcreteFlyweight implements Flyweight {
    -intrinsicState
    +operation(extrinsicState)
}

class UnsharedConcreteFlyweight implements Flyweight{
    -fullState
    +operation(extrinsicState)
}

Client -> FlyweightFactory
FlyweightFactory "*"*-> Flyweight
@enduml
