@startuml interpreter
hide empty members
class Client{}

interface AbstractExpression {
    +interpret(context: Context)
}

class TerminalExpression implements AbstractExpression {
    +interpret(context: Context)
}

class NonTerminalExpression implements AbstractExpression {
    -nextExpression: AbstractExpression
    +interpret(context: Context)
}

class Context {}

Client -> Context
Client --> AbstractExpression
NonTerminalExpression o--> AbstractExpression
@enduml
