@startuml mediator
hide empty members

interface Mediator {
    +notify(sender: Component)
}

class ConcreteMediator implements Mediator {
    +notify(sender: Component)
}

abstract class Component {
    -mediator: Mediator
    +setMediator(mediator: Mediator): void
}

class ConcreteComponentA extends Component {}
class ConcreteComponentB extends Component {}

Component -> Mediator
ConcreteComponentA <- ConcreteMediator
ConcreteComponentB <- ConcreteMediator
@enduml
