@startuml prototype
hide empty members

class Client{
    +operation()
}

interface Prototype {
    +clone(): Prototype
}

class ConcretePrototype implements Prototype {
    +clone(): ConcretePrototype
}


Client -> Prototype : prototype
@enduml
