@startuml proxy
hide empty members

class Client{}

interface Subject {
    +operation()
}

class RealSubject implements Subject {
    +operation()
}

class Proxy implements Subject {
    -realSubject: RealSubject
    +operation()
}

Client -> Subject
Proxy -> RealSubject
@enduml
