@startuml singleton
hide empty members

class Singleton {
    -uniqueInstance: Singleton
    -singletonData: Data
    -Singleton(): Singleton
    +getSingletonData(): Data
    +instance(): Singleton
    +singletonOperation()
}
@enduml
