@startuml strategy
hide empty members

interface Strategy {
    +execute() 
}

class ConcreteStrategyA implements Strategy {
    +execute() 
}

class ConcreteStrategyB implements Strategy {
    +execute()
}

class Context {
    -strategy: Strategy
    +setStrategy(strategy: Strategy): void
    +executeStrategy()
}

Context o-> Strategy
@enduml
