@startuml template_method
hide empty members
abstract class AbstractClass {
    +templateMethod()
    +primitiveOperation1()
    +primitiveOperation2()
}

note right of AbstractClass::templateMethod
    ...
    primitiveOperation1();
    ...
    primitiveOperation2();
    ...
end note

class ConcreteClass extends AbstractClass {
    +primitiveOperation1()
    +primitiveOperation2()
}

@enduml
